name: Release and Publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  release-and-publish:
    name: Release and Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/advanced-yaml
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Setup environment with uv
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e .[dev]

      - name: Check and Tag Version
        id: tag_version
        run: |
          source .venv/bin/activate
          VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
          TAG="v$VERSION"
          echo "TAG_NAME=$TAG" >> $GITHUB_ENV
          
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists locally."
          else
            echo "Tag $TAG does not exist. Creating..."
            git tag -a "$TAG" -m "Release $TAG"
          fi
          
          if git ls-remote --exit-code --tags origin "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists on remote."
          else
            echo "Pushing tag $TAG to remote..."
            git push origin "$TAG"
          fi

      - name: Build package
        run: |
          uv run python -m build

      - name: Draft Release Notes
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          tag: ${{ env.TAG_NAME }}
          version: ${{ env.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          draft: false
          tag_name: ${{ env.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
